### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by vVwd** [cyanobacterium/OreSpawn#1]
http://pastebin.com/zijKx4jE

**Comment by jriwanek** [comment]
"Ore block with ID nethermetals:nether_copper_ore does not exist!"

Either add back nether metals to the pack you're using or remove:
nethermetals-bmores.json
and
nethermetals-mmores.json

from config/orespawn.

**Comment by vVwd** [comment]
Odd, I removed all the config stuff before reloading the pack I am working on.

Will have a look tomorrow, late here. Thanks for the pointer.

**Comment by jriwanek** [comment]
No problem.

**Comment by vVwd** [comment]
My bad, BaseMetals is the cause. Thanks. :)

**Comment by vVwd** [comment]
If I remove the file you suggested, it crashes after reboot. If I remove all the configs in general, same thing. 

Basicly, if I have end metals & ore spawn, all fine. Base metals & ore spawn, all fine. The 3 together, it crashes. If you need zip of the pack, just let me know. nn

**Comment by jriwanek** [comment]
Would be helpful

**Comment by vVwd** [comment]
Here you go. After updating this morning:

http://pastebin.com/dA1iZtrY

https://mega.nz/#!pws2nTiZ!MA1jHAiVmLOpfRHFxLZvsGR5nRqGsN-mv9Jdhj9RNWA

Ore spawn + Base = crash
Ore spawn + End = crash
Base + End = working

**Comment by jriwanek** [comment]
Checked it over, edit endmetals-bmores and endmetals-nmores and change nether_\* to end_*, I'm pushing a new release to curseforge shortly which fixes it. problem actually in end-metals, not orespawn.

**Comment by jriwanek** [comment]
end-metals 1.0.2 released to curseforge, should be available soon.
