### ISSUE TITLE
[1.9.4] Retrogen option

### ISSUE THREAD

**Issue by ruyanve** [cyanobacterium/OreSpawn#4]
I'd love to add another ore to our world, but it seems there is no retro gen option. I had a look at https://github.com/cpw/simpleretrogen but there seems to be no easy way to tell what's the right generator for the specific ore I want.

Cheers

**Comment by Mohron** [comment]
I also just thought of this. Would be nice as an addition setting under every ore. If it's set to true the mod will RetroGen only those ores and change the config back to false. 
**EX:**

```
"retroGen":false (do nothing)
"retroGen":true (retrogen specific ore and change retroGen to false)
```

**Comment by jriwanek** [comment]
Retrogen is available in the latest 3.x releases now.
