### ISSUE TITLE
The ores are not spawning using this custom config on a MC 1.10.2 server 

### ISSUE THREAD

**Issue by knoxhack** [cyanobacterium/OreSpawn#5]
Using this config, and running on forge Build 1.10.2-12.18.0.2006-1.10.0.

The ores are not spawning using this custom configs in a server 
They spawn as the default base metals config.

https://gist.github.com/knoxhack/a4dee6786ddaff5f83090bb1341e7e53

**Comment by jriwanek** [comment]
You have to use the same file name to overide the default config, so in this case you'd be wanting "basemetals.json"

**Comment by knoxhack** [comment]
I do have the same one. I edited the one that the mod generated

**Comment by knoxhack** [comment]
/config/orespawn','basemetals.json

**Comment by knoxhack** [comment]
The was generated back im 1.9.4 tho. i might have to generate a new one

**Comment by jriwanek** [comment]
Okies, lemme know, it may be overwriting the config file.

**Comment by critchards** [comment]
Im having a similar issue. 1.10.2 Im getting partial generation of ores using config files but it does not seem to be respecting the biome list.
[minecraft.txt](https://github.com/cyanobacterium/OreSpawn/files/514796/minecraft.txt)
It was a .json file, couldnt save it to Github without converting it. Sorry, Im new at this.

Im trying to use multiple generators per ore type. For instance I want iron to spawn everywhere at low concentrations and in extreme hills as dense clusters. The generation everywhere works, the biome restricted generation only works if I add biome ID 4 (forest) and then it adds the generators to all other biomes as well.  Doesnt seem to like any of the hill type IDs.

Im probably doing something wrong, any suggestions would be appreciated.

**Comment by jriwanek** [comment]
Newer OS releases have changed things, closing antiquated issue due to lack of activity in comments.
