### ISSUE TITLE
Base Metals not spawning in modpack when other Orespawn metals are.

### ISSUE THREAD

**Issue by Sukid** [cyanobacterium/OreSpawn#6]
Basically every .json I have in the orespawn configs folder I have works except for Base Metals. The Base Metals themselves are in the game, they can be found in JEI and in loot chests, but for some reason no matter what I do they will not spawn. If a mod is causing this I haven't tracked it down yet, as I've disabled most mods I have that affect worldgen in a big way and this problem persists. I did turn on forge oregen and even turned off "use orespawn" in the base metals config incase that would do something paradoxically. Still nothing.

I can get it to work in an isolated forge profile and that's basically it.

These are the mods I'm using in my pack:
http://www.modlister.com/user/Sukid

**Comment by Sukid** [comment]
Also, as far as the Forge log is concerned everything is fine. It doesn't mention any problems as far as I could tell with Base Metals.

**Comment by jriwanek** [comment]
I'll take a look into it.

**Comment by Sukid** [comment]
Thanks. Sorry for hitting both this one and the base metals issue tracker. I posted it here first then realized it might be more relevant to base metals, but either way it doesn't make much sense.

**Comment by Sukid** [comment]
Okay I should probably point out that what DID work was just running a forge profile without ANY of my modpack's pre-existing config files. For whatever reason, that worked and the base metals spawned just fine. Mysterious,

**Comment by jriwanek** [comment]
Can I consider this closed?

**Comment by jriwanek** [comment]
Closing due to lack of response.
