### ISSUE TITLE
1.10.2 version?

### ISSUE THREAD

**Issue by miiichael** [cyanobacterium/OreSpawn#7]
Any chance of a release for the current Minecraft version? Thanks!

**Comment by jriwanek** [comment]
I've been using the 1.9.4 version on 1.10.2 for ages, it works fine, give it a try aswell and let me know if you have any trouble.

**Comment by miiichael** [comment]
Ah, if you reckon the 1.9.4 version should work unchanged then I suggest adding the appropriate 1.10 tag(s) to the file release on curseforge.

**Comment by jriwanek** [comment]
I would but cyano hasn't given me perms on that project yet and he's not been around for a while.

**Comment by jriwanek** [comment]
A 1.10.2 version has been out for a while now.
